version: 0.2
phases:
  pre_build:
    commands:
      - echo "Checking directory structure..."
      - ls -R
      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo "Building Docker images..."
      - docker build -t itomata-frontend frontend/
      - docker build -t itomata-backend backend/
  post_build:
    commands:
      - echo "Pushing images to ECR..."
      - docker tag itomata-frontend:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/itomata-frontend:latest
      - docker tag itomata-backend:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/itomata-backend:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/itomata-frontend:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/itomata-backend:latest
      - echo "Updating EKS deployment via Blue/Green script..."
      - aws eks update-kubeconfig --region ap-south-1 --name itomata-eks-cluster
      - aws sts get-caller-identity
      # UPDATED: Give the script execution permissions and run it
      - chmod +x deploy.sh
      - ./deploy.sh
      - echo "Blue/Green Deployment complete!"
