apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::795732143548:role/itomata_nodes-eks-node-group-20260226083801075700000003
      groups:
        - system:bootstrappers
        - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::795732143548:role/itomata-codebuild-role
      groups:
        - system:masters
        - username: codebuild
    - rolearn: arn:aws:iam::795732143548:role/itomata-codebuild-role-us-east-1
      groups:
        - system:masters
      username: codebuild-us
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
