apiVersion: apps/v1
kind: Deployment
metadata:
  name: itomata-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: itomata-backend
  template:
    metadata:
      labels:
        app: itomata-backend
    spec:
      containers:
        - name: backend
          image: 795732143548.dkr.ecr.ap-south-1.amazonaws.com/itomata-backend:latest
          ports:
            - containerPort: 5000

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"

          startupProbe:
            httpGet:
              path: /api/status
              port: 5000
            failureThreshold: 12
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /api/status
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 2

          livenessProbe:
            httpGet:
              path: /api/status
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 2
