apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: itomata-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    # The deploy.sh script will replace this with the active version (v1 or v2)
    name: itomata-app-VERSION_PLACEHOLDER
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          # Scale up if average CPU usage across pods exceeds 50%
          type: Utilization
          averageUtilization: 50
