# 1. FRONTEND SERVICE (Points to Nginx)
apiVersion: v1
kind: Service
metadata:
  name: itomata-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: itomata
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
# 2. BACKEND SERVICE (Points to Flask)
apiVersion: v1
kind: Service
metadata:
  name: itomata-backend-service
spec:
  type: LoadBalancer
  selector:
    app: itomata
  ports:
    - protocol: TCP
      port: 80 # The URL will still be http://... (no :5000 needed)
      targetPort: 5000 # This specifically tells K8s to find the Flask container
